export interface iCocktail {
    idDrink: string;
    strDrink: string;
    strDrinkAlternate?: null;
    strTags?: string | null;
    strVideo?: null;
    strCategory: string;
    strIBA?: string | null;
    strAlcoholic: string;
    strGlass: string;
    strInstructions: string;
    strInstructionsES?: null;
    strInstructionsDE?: string | null;
    strInstructionsFR?: null;
    strInstructionsIT?: string | null;
    strDrinkThumb: string;
    ingredientList: string[];
    strIngredient1: string;
    strIngredient2: string;
    strIngredient3: string;
    strIngredient4: string;
    strIngredient5: string;
    strIngredient6?: string | null;
    strIngredient7?: string | null;
    strIngredient8?: null;
    strIngredient9?: null;
    strIngredient10?: null;
    strIngredient11?: null;
    strIngredient12?: null;
    strIngredient13?: null;
    strIngredient14?: null;
    strIngredient15?: null;
    strMeasure1: string;
    strMeasure2: string;
    strMeasure3: string;
    strMeasure4: string;
    strMeasure5?: string | null;
    strMeasure6?: string | null;
    strMeasure7?: string | null;
    strMeasure8?: null;
    strMeasure9?: null;
    strMeasure10?: null;
    strMeasure11?: null;
    strMeasure12?: null;
    strMeasure13?: null;
    strMeasure14?: null;
    strMeasure15?: null;
    strImageSource?: string | null;
    strImageAttribution?: string | null;
    strCreativeCommonsConfirmed: string;
    dateModified?: string | null;
    "strInstructionsZH-HANS"?: null;
    "strInstructionsZH-HANT"?: null;
  }
  